### ISSUE TITLE
HTTP 400 on every post request from the UI

### ISSUE THREAD

**Issue by LennyPenny** [linuxserver/docker-jackett#63]
Every post request sent to jackett results in a 400 error with an empty response. 
I can't even turn on the enhanced logging as the post request to update the settings fails as well. 

There are no logs after Jacketts successful start and loading of the indexers. 

I also checked all file permissions, they are correctly being set to 1000 on the host.

Here's my docker-compose for it: 
```
jackett:
    container_name: jackett
    image: "linuxserver/jackett"
    restart: always
    networks:
      - torrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 9117:9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/gits/sonarr/config:/config
      - ~/rtorrent/torrents:/downloads
```

Some logs about the used versions: 
```
12-13 22:36:50 Info Starting Jackett v0.10.504.0
12-13 22:36:50 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
12-13 22:36:50 Info OS version: Unix 4.9.0.8 (64bit OS) (64bit process)
12-13 22:36:50 Info ThreadPool MaxThreads: 800 workerThreads, 200 completionPortThreads
12-13 22:36:50 Info App config/log directory: /config/Jackett
12-13 22:36:50 Info issue: Ubuntu 16.04.5 LTS \n \l
12-13 22:36:50 Info mono version: 5.16.0.220 (tarball Mon Nov 26 17:22:46 UTC 2018)
```

Here's a screenshot of the failed request to enable enhanced logging: 
![https://vgy.me/JoVApx.png](https://vgy.me/JoVApx.png)

Do you have any idea what might be going wrong?
