### ISSUE TITLE
unable to download torrents locally.

### ISSUE THREAD

**Issue by Troubadoure** [linuxserver/docker-jackett#88]
When doing a manual search I can download a torrent to the blackhole, however clicking on the download locally button does nothing. Furthermore getting the url from the download link and entering that into an address bar returns nothing.

**Comment by Troubadoure** [comment]
Host OS: Mac
Jackett Version 0.11.487.0
docker-compose file:
```
version: '3'
services:
  transmission:
    container_name: Transmission
    image: haugene/transmission-openvpn:latest
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
    cap_add:
      - net_admin
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports: 
      - "9091:9091"
      - "9117:9117"
      - "8989:8989"
      - "7878:7878"
    volumes:
      - ./data:/data
      - ./NAS/Downloads:/Downloads
      - ./Downloads:/Misc
      - ./ssh:/config/.ssh
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ...truncated
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett:latest
    container_name: Jackett
    depends_on: 
      - transmission
    network_mode: service:transmission
    environment:
      - PUID=501
      - PGID=20
      - TZ=****
    volumes:
      - ./NAS/Downloads/blackhole:/downloads
      - ./NAS/docker/Jackett:/config
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: Sonarr
    depends_on: 
      - transmission
      - jackett
    network_mode: service:transmission
    environment:
      - PUID=501
      - PGID=20
      - TZ=****
    volumes:
      - "./NAS/Plex/TV Shows:/tv"
      - ./NAS/Downloads:/downloads
      - ./NAS/docker/Sonarr:/config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: Radarr
    depends_on:
      - transmission
      - jackett
    network_mode: service:transmission
    environment:
      - PUID=501
      - PGID=20
      - TZ=****
    volumes:
      - ./NAS/Plex/Movies:/movies
      - ./NAS/Downloads:/downloads
      - ./NAS/docker/Radarr:/config
    restart: unless-stopped
```

logs:

```
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
07-18 12:37:26 Info Found 3 (1 new) releases from The Pirate Bay 
07-18 12:37:26 Info Found 100 (1 new) releases from RARBG 
07-18 12:37:30 Info Found 50 (1 new) releases from 1337x 
07-18 12:52:57 Info Found 50 (0 new) releases from 1337x 
07-18 12:53:02 Info Found 100 (0 new) releases from RARBG 
07-18 12:53:24 Info Found 6 (4 new) releases from The Pirate Bay 
07-18 13:08:52 Info Found 5 (1 new) releases from The Pirate Bay 
07-18 13:08:54 Info Found 50 (3 new) releases from 1337x 
07-18 13:08:58 Info Found 100 (4 new) releases from RARBG 
07-18 13:10:44 Info Found 50 (0 new) releases from 1337x 
07-18 13:10:45 Info Found 15 (10 new) releases from The Pirate Bay 
07-18 13:10:47 Info Found 100 (100 new) releases from RARBG 
07-18 13:16:25 Info Manual search for "American Dad" on 1337x, rarbg, thepiratebay with 230 results. 
```

Not using any symlinks
